### ISSUE TITLE
Decorator is missing in types 

### ISSUE THREAD

**Issue by 4FunAndProfit** [buddh4/mapped-types#58]
What a wonderful library you made! 

Yet, for me it is unusable because the types are missing decorator : for example: 

- yours: `export declare function PickType<T, K extends keyof T>(classRef: Type<T>, keys: readonly K[]): Type<Pick<T, typeof keys[number]>>;`
- nestjs: `export declare function PickType<T, K extends keyof T>(classRef: Type<T>, keys: readonly K[], decorator?: ClassDecoratorFactory): Type<Pick<T, (typeof keys)[number]>>;`

Is it possible to add this to your types ? 

Thanks a lot in advance!! :)

**Comment by buddh4** [comment]
Hi, sorry missed this one, I'll have a look when I find the time ;)

**Comment by 4FunAndProfit** [comment]
Hello @buddh4 !

I think it's me who is Wrong ! (That's why I close it)

In nestjs it is already done for the transmission of class-validator, isn't it ?

This définition of class is from nestjs/graphql but in fact I think it is not necessary then?

That's why I think it is ok and can be closed ?
